seed: 3072

model:
  image_size: 224
  patch_size: 14
  embed_dim: 192

data:
  frame_skip: 5
  sequence_length: 3

training:
  batch_size: 128
  num_epochs: 100
  learning_rate: 0.00005
  weight_decay: 0.001

loss:
  sigreg_weight: 0.09